#!/bin/bash

# Individual, Money, And Society doesn't use the MC component, so it's
# removed/ commented out  -noah

set -e

./install-mpf-dependencies
#./install-mc-dependencies

# Forked Git Repo of MPF
python3.8 -m pip install -e git+git://github.com/diydsp/mpf.git@dev#egg=mpf
# pip3 install --upgrade mpf
#pip3 install --upgrade mpf mpf-mc
